### ISSUE TITLE
"Not available" message for translate of "LibreTranslate"

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate-flutter-client#69] opened 2021-09-21 16:33 UTC
Steps:

1. Set the instances to `almaleehserver.asuscomm.com:447`.
2. Switch to "LibreTranslate" translator.

After this operation, I got a constant "Not available" message in "LibreTranslate".. Regardless of the subsequent instance selection. After removing the memory for the application, the problem persists.

**Comment by Valdnet** [comment] 2021-09-21 18:06
Something went wrong with the application. I am also unable to translate in "GoogleTranslate". Only the translation loading window is shown.

![obraz](https://user-images.githubusercontent.com/47037905/134223714-93bd07f2-ea08-4018-8086-a8ead2eeff77.png)

![obraz](https://user-images.githubusercontent.com/47037905/134223776-ed5a2b80-b1b9-45b6-816d-f095ee687923.png)

I just changed the instance from `translate.metalune.xyz` to `almaleehserver.asuscomm.com:447`. Going back to the previous instance will do nothing. It does not work on either instance now.

**Comment by ManeraKai** [comment] 2021-09-21 18:08
https://github.com/ManeraKai/simplytranslate-flutter-client/issues/65

**Comment by Valdnet** [comment] 2021-09-21 18:11
I don't understand why translation does not work on my version of the application if the changes were only made to the design for the new application. Does it have to do with the settings on the server (yours)?

**Comment by ManeraKai** [comment] 2021-09-21 18:14
It's because this domain doesn't work anymore `translate.metalune.xyz`. And I need to release a fix for it to F-Droid because this is really important.
btw: Here is a link for the instance updated version: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1258777464

**Comment by Valdnet** [comment] 2021-09-21 18:19
How does it not work? After all, it redirects from the domain [translate.metalune.xyz](http://translate.metalune.xyz) to the domain [simplytranslate.org](https://simplytranslate.org). Something's not right for me. Can you explain it more?

**Comment by ManeraKai** [comment] 2021-09-21 18:24
I think redirecting works in browsers, but not with classic http requests. I think directing is not a response and the http package won't accept it. There is an option for redirecting though in the http package.

**Comment by Valdnet** [comment] 2021-09-21 18:37
> btw: Here is a link for the instance updated version: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1258777464

File error (corrupted).

**Comment by ManeraKai** [comment] 2021-09-21 18:43
Note: the issue is still there. You should select an instance from the list and then translate.

**Comment by metalune1** [comment] 2021-09-21 20:17
Hi, I'm the owner of simplytranslate.org/translate.metalune.xyz, I'll be working on making translate.metalune.xyz a proxy to simplytranslate.org so the domain change doesn't break everything, I just haven't found the time yet as it's been getting kind of late here

**Comment by ManeraKai** [comment] 2021-09-21 20:21
If you make it like a proxy instead of redirecting to the other domain, it won't break the F-Droid app. This will let me polish the app more before adding another release for just this thing. I'll really appreciate it if you did that.

**Comment by ManeraKai** [comment] 2021-09-21 20:24
Great, Thanks!

**Comment by metalune1** [comment] 2021-09-21 20:25
It's up again :D I'll probably work on adding a depreceation notice to the website soon, as this domain should no longer be used, but yeah, I'll keep it for legacy purposes now.

**Comment by Valdnet** [comment] 2021-09-22 06:29
@metalune1 I greet you :wave:. It's great that you run this server. I think that your server plus the ManeraKai application is a very successful idea and you will both gain many users quickly. This was missing for translators. Thanks a lot 👍.

It works fine at the moment.

**Comment by metalune1** [comment] 2021-09-22 07:33
You're welcome, for this to become a successful project we still need more instances though, I fear that if we gain too much popularity my server will end up on a blocklist by google (at which point I'll probably make it a proxy to a random working server each time you access it to spread the load)

**Comment by ManeraKai** [comment] 2021-09-23 16:39
@Valdnet I'll close this one as this problem was removed with it's feature. Updating instances list from the official server was added here #65

**Closed by ManeraKai** 2021-09-23 16:39 UTC
